name: "fast-food-app"

services:
  users_db:
    container_name: users_db
    image: postgres:17
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}